### PR TITLE
Prevent need to do npm install --force when using Carbon Charts with a modern Angular project (15.1.5)

### PR DESCRIPTION
**Pull request by nstuyvesant**
### Updates
- Changed peerDependencies to use ">=" on lowest versions supported. It works with the latest and has not broken from updates to Angular, RxJS, and zones.js. Having to always use `npm install --force` because of Carbon Charts is tedious.

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by nstuyvesant** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by theiliad — CHANGES_REQUESTED** [review]
Hi, this technically will allow any future versions before we get a chance to inspect them.

Could you please expand on what kind of issues the current declarations are causing? 🙂

**Comment by nstuyvesant** [comment]
We use Angular 15.1.4. As a result, `npm install` fails...
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @carbon/charts-angular@1.6.4
npm ERR! Found: @angular/common@15.1.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^15.1.4" from the root project
npm ERR!   peer @angular/common@"^15.0.0 || ^16.0.0" from @angular/cdk@15.1.4
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^15.1.4" from the root project
npm ERR!     peer @angular/cdk@"15.1.4" from @angular/material@15.1.4
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^15.1.4" from the root project
npm ERR!       1 more (ng-table-virtual-scroll)
npm ERR!     1 more (ng-table-virtual-scroll)
npm ERR!   11 more (@angular/forms, @angular/material, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0" from @carbon/charts-angular@1.6.4
npm ERR! node_modules/@carbon/charts-angular
npm ERR!   @carbon/charts-angular@"^1.6.4" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/common@14.2.12
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^6.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0" from @carbon/charts-angular@1.6.4
npm ERR!   node_modules/@carbon/charts-angular
npm ERR!     @carbon/charts-angular@"^1.6.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/nates/.npm/_logs/2023-02-22T16_38_38_561Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nates/.npm/_logs/2023-02-22T16_38_38_561Z-debug-0.log
```

We know Carbon Charts works fine with Angular 15.1.4 so we have to do an `npm install --force`. But the problem is that may mask a compatibility issue that is a problem.

As Google releases new versions of Angular very frequently (and we have to test against the latest), Carbon Chart's explicit peerDependencies always lags behind.

Hope this helps clarify the problem I'm trying to solve.

**Comment by theiliad** [comment]
> We use Angular 15.1.4. As a result, `npm install` fails...

Thanks for that context. Seems like adding `|| ^15.0.0` to our package.json will fix the issue without actually opening the door to all future versions before inspection. Would that work?

**Comment by nstuyvesant** [comment]
That would work (until whenever Google decides to release 16) ;-)

**Comment by nstuyvesant** [comment]
Created a separate PR using < 16.0.0 as the minor Angular updates have not been creating problems for Carbon Charts.

**Pull request closed without merging**
