### PR TITLE
docs: update install instructions

### PR DESCRIPTION
**Pull request by tay1orjones**
### Updates
- Remove instruction to install core package when installing framework packages. The framework packages already have `@carbon/charts` as a hard dependency.
- Update the remote url in the contributing docs

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/IBM/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by tay1orjones** [comment]
Looks like I forgot to turn off Prettier in my editor so some reformatting slipped in alongside my changes. I can remove/revert it - just let me know.

**Comment by theiliad** [comment]
@tay1orjones your PR seems to have gauge-related logic in there which hasn't been merged yet

**Comment by tay1orjones** [comment]
@theiliad 🤔 It didn't initially. I created my branch off `master`.

Could it be the result of @natashadecoste force push from yesterday listed in the history above?

> image

**Comment by theiliad** [comment]
> @theiliad 🤔 It didn't initially. I created my branch off `master`.
> 
> Could it be the result of @natashadecoste force push from yesterday listed in the history above?
> 
> > image

probably. we'll need to take out the gauge logic anyways, sorry!

**Comment by theiliad** [comment]
I applied your proposed changes manually, thanks @tay1orjones

**Pull request closed without merging**
