### PR TITLE
Composable diagram components

### PR DESCRIPTION
**Pull request by j1mie**
Adds base-level components for composing graphs and diagrams. 

This is not a "batteries included" approach to creating graphs: As graphing experiences are often divergent in intent, content, layout and interaction. 

These UI components should serve as building blocks for consumers to roll their own experiences, incorporating Carbon components.

**Adds**
- React and Angular components and stories for Card, Circle, Edge
- React and Angular storybook examples for static graph drawing using these components
- Styles and utility functions for the above components, in the core package

**Updates**
- Bumps React version to make use of hooks.

**Todo / Next steps**
- Examples for using these components with third party libraries in CodeSandbox
- PanZoom component

### CODE REVIEW

**Comment by TerraLBanal** [comment]
Hi @j1mie & @theiliad a couple design updates. (that we talked about in the meeting this morning)


**Default circle node should have [body-short-01] [text-01]**
Instead of [heading-01] 
Screen Shot 2021-06-03 at 11 35 37 AM

**Please use [heading 01] on hover instead**
Screen Shot 2021-06-03 at 1 49 28 PM

---

There is a slight color difference behind the overflow menu 
Screen Shot 2021-06-03 at 11 30 15 AM

---

Check carbon focus state. (Should be 2px blue outline?) 
Screen Shot 2021-06-03 at 11 35 53 AM

---

Other than that, @cameroncalder, Diana and I need to sync on the spacing inside of node, grouped node styling, spacing around overflow menu and 1.5 vs. 1px line weight for edges (connection lines)

Let me know if you all have any other thoughts or questions. Thanks!

**Review by theiliad — CHANGES_REQUESTED** [review]
My ideas so far:
1. A little bit of documentation
2. Removing the examples and packages like `elk` to add to codesandboxes once we merge
3. Moving utilities into `core`
4. More descriptive utility naming, e.g. `generateBezierPathString`
5. Moving `scss` files into a `diagrams` directory
6. Renaming `graph` to `Diagrams` (storybook, directories)

**Review by natashadecoste — COMMENTED** [review]
looks good to me so far, should move packages/react/src/components/graph/notes.md before merging

**Comment by j1mie** [comment]
Hey @TerraLBanal quick question on the circle node — Does the component still have two text properties: title and description? 

image

**Review by theiliad — CHANGES_REQUESTED** [review]
Hi @j1mie
The angular stories don't load, if you run 'yarn demo:build' inside the angular directory, you should be able to see the error

**Comment by j1mie** [comment]
Hi @theiliad I'll take a look, thanks.

**Comment by j1mie** [comment]
@TerraLBanal I have updated the focus state; re: the comment above, does the circle node include two lines of text? Thanks 🔥

**Comment by j1mie** [comment]
@cameroncalder FYI I updated the CardNode component to include a more modular approach as seem in the ListItem component you showed me. Consumers of this component can now nest any other components within columns of this card.

**Comment by TerraLBanal** [comment]
@j1mie A couple other decisions we made with the spacing and line weight. 

1. We increased the spacing inside of the nodes to 16 px all the way around and between the text & icon. (It's more consistent with the notification in carbon and what the visual programming team is working on. 

Screen Shot 2021-06-08 at 4 27 25 PM

---

2. We decided to go with 1px weight for the default edges / lines. In some of the use cases 1.5 was looking a little too thick, especially when hovering / selecting. 

Screen Shot 2021-06-08 at 4 27 50 PM


Let me know if that works for you all! Thanks. : )

**Comment by j1mie** [comment]
Hey @TerraLBanal updated the PR with the following:
- Spacing changes to cards
- Size 20 icon in all examples
- Edge stroke width set to 1px
- Changes to type based on the above feedback

@theiliad the angular command you posted above works okay locally, wondering if this is some memory issue?

**Comment by theiliad** [comment]
@j1mie hmmm... `yarn demo:build` inside the `angular` package errors out for me locally, which I'm trying to fix.

This usually wouldn't be related to the storybook caching issues

**Comment by theiliad** [comment]
> @j1mie hmmm... `yarn demo:build` inside the `angular` package errors out for me locally, which I'm trying to fix.
> 
> This usually wouldn't be related to the storybook caching issues

@j1mie after a couple of days of spinning around, I was able to fix the storybook issue. If only storybook was better with explaining why it breaks...

**Comment by theiliad** [comment]
> > @j1mie hmmm... `yarn demo:build` inside the `angular` package errors out for me locally, which I'm trying to fix.
> > This usually wouldn't be related to the storybook caching issues
> 
> @j1mie after a couple of days of spinning around, I was able to fix the storybook issue. If only storybook was better with explaining why it breaks...

@j1mie @TerraLBanal I also added this to the tutorial examples
image

**Comment by theiliad** [comment]
@j1mie we good to merge?

**Comment by j1mie** [comment]
@theiliad Amazing! Please feel free to assign two issues to me, for:
- CodeSandbox demos
- PanZoom component

Thanks for getting this over the line!

**Comment by theiliad** [comment]
@j1mie I just added a react sandbox here #1047, feel free to update that or change it, but more importantly also lmk if you're able to create one for angular or at least provide some sample code in the storybook

**Comment by j1mie** [comment]
Hey @theiliad here's the sample code https://github.com/j1mie/carbon-charts/tree/f83386bbcb6b00bd15665723f411618c142381d3/packages/angular/src/components/graph/codepen_examples/elk

**Pull request merged**
