### PR TITLE
[WIP] : Area chart 

### LINKED ISSUE #188: Area Chart
#### I am submitting a...

- [X] Feature request
- [ ] Design defect
- [ ] Source code defect
- [ ] Demo/documentation defect
- [ ] Other

### PR DESCRIPTION
**Pull request by darsi-an**
### Updates
- Implements Area chart functionality
- x scale implemented using continuous time scale
- Implements hover and move to front based on mouse-over tool-tip
- Area Chart, closes #188 

### In Progress
- Legend functionality for area charts (in reference to the charting guide)
- Fix grid line calculation, update data, and transitions

### Questions for reviewers
- I have placed the function `setXAxis(noAnimation?: boolean)` in area-chart to not break the other charts in the demo. I want to point out the only line of code we would need for support continuous time scales (**for the x-axis**) is
   - `.tickFormat(timeFormat("%Y/%m/%d")).tickValues(this.displayData.labels.map(dataset => formatTime(dataset)));`

   - However, you would still need to set the xScale passing date objects. I have done this using d3-time-format. Tick format, as in its name, sets the format while tickValues limits the x-axis to that in your domain. 

   - I can move on with adding support for continuous time scales, but I will require more details on the design. Specifically, how developers would developers set the type of continuous scale. Such as a flag in the configurations.

- How should the legend work for area charts? Will legend selections remove elements or highlight the area of the selected legend element?

### Demo screenshot or recording
- The demo implements area-chart using continuous time scale. 
- Currently legend is set as not clickable for demo purposes and to seek feed back on design correctness.  
- Please note this is still in progress.
 
### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/IBM/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by theiliad** [comment]
Also, very detailed PR description, thank you 💯

**To answer your questions:**
> I want to point out the only line of code we would need for support continuous time scales...
That is the way to get the axis to support that format, but there's more to be done to support ranges of date based data etc.

> I can move on with adding support for continuous time scales...
That'd be great, but we should discuss the details, also it should be in a separate PR, ideally a PR should be for 1 task.

> How should the legend work for area charts? Will legend selections remove elements or highlight the area of the selected legend element?
@dianatran18 Do we have an answer to this?

**Comment by darsi-an** [comment]
> It's a great start 👍
> 
> I haven't reviewed the code but have a few points based on the deploy preview:
> 
> 1. According to specs, fill-opacity should be at 80% for all the areas.
> 2. Great job on the move to front feature 💯
> 3. We need to find a way around this:
>    image
>    Hoping that @dianatran18 can chime in with that^^
> 4. Resize seems to be broken, as well as update data
> 5. The legend doesn't seem to be working either

Thanks @theiliad  for the quick response. 
1. I'll update the opacity according to specs
4. Yup, ill definitely add this to my in progress tasks
5. I've currently set legend to not clickable as I would like more feed back on how legend functionality should work for area charts.
    - do clicks highlight or remove elements?

**Comment by theiliad** [comment]
Quick thought, fill opacity should be at 80% by default like the specs suggest, but they also should be customizable through the chart configs

**Comment by theiliad** [comment]
Sidenote, how feasible is it to implement gradient fills for the areas?

**Comment by darsi-an** [comment]
> Quick thought, fill opacity should be at 80% by default like the specs suggest, but they also should be customizable through the chart configs

Noted. I will make sure to follow specs and include customizeable fill opacity through chart configs. 

> Sidenote, how feasible is it to implement gradient fills for the areas?

Not sure, but I will look into it and see if it will be feasible to include with with this PR.

**Comment by darsi-an** [comment]
@theiliad I've removed the continuous time scale and based it off current implementations. I'll open an feature request for continuous scales that are to be supported.  Check out the demo, let me know if there any any changes that need to be made. 

Note, Im working on setting custom opacity in chart configs.

**Comment by theiliad** [comment]
@darsi-an I closed this PR for now since it's been inactive for a long time. Let me know if you'd still like to work on it and we can re-open.

**Pull request closed without merging**
