### PR TITLE
chore(package.json): explicitly state yarn and node 16

### PR DESCRIPTION
**Pull request by nstuyvesant**
### Updates
Added engines to package.json to make the required dev environment a little more explicit. While there's an .nvmrc for node,  engines are a little more explicit and visible as they appear where all the packages versions are listed.

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Review by theiliad — CHANGES_REQUESTED** [review]
Hi @nstuyvesant, v14.x seems a bit dated for node (LTS being at 18.x). Maybe we go to at least 16.x?

**Comment by nstuyvesant** [comment]
Was using the value you already had in your .nvmrc (14) but I agree that is really old. if it's to be changed, I would go with 18.14.2 as it is LTS.

Out of curiosity, what Node and Python versions have you been using for this package?

**Comment by nstuyvesant** [comment]
Node.js v14 is planned to be End-of-Life on 2023-04-30. Angular will stop supporting Node.js v14 in Angular v16.

**Review by theiliad — APPROVED** [review]
LGTM

**Comment by theiliad** [comment]
> Was using the value you already had in your .nvmrc (14) but I agree that is really old. if it's to be changed, I would go with 18.14.2 as it is LTS.
> 
> Out of curiosity, what Node and Python versions have you been using for this package?

I don't really use python, but for node I'm using `16.19.0`. We can test with 18.x as well, and if it works then it should be ok to update

**Comment by nstuyvesant** [comment]
Oh... gotcha. I did that as a separate PR.

**Comment by theiliad** [comment]
@nstuyvesant also the github workflow needed to be updated https://github.com/carbon-design-system/carbon-charts/commit/09b7f6af044ca3195cc965e99940a7347699284b

**Comment by theiliad** [comment]
@nstuyvesant Seems like github workflow gets stuck on the vue build

**Comment by nstuyvesant** [comment]
Where can I find the error messages for it? I didn't see it above.

**Comment by theiliad** [comment]
The jobs just get stuck, there's no error https://github.com/carbon-design-system/carbon-charts/actions/runs/4345700538/jobs/7593603059

**Comment by nstuyvesant** [comment]
Yep - that’s what I’m seeing locally…

@carbon/charts-angular: ------------------------------------------------------------------------------
@carbon/charts-vue:  WARNING  Compiled with 3 warnings5:48:21 PM
@carbon/charts-vue:  warning  
@carbon/charts-vue: asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
@carbon/charts-vue: This can impact web performance.
@carbon/charts-vue: Assets: 
@carbon/charts-vue:   charts-vue.umd.min.js (617 KiB)
@carbon/charts-vue:  warning  
@carbon/charts-vue: entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
@carbon/charts-vue: Entrypoints:
@carbon/charts-vue:   charts-vue.umd.min (617 KiB)
@carbon/charts-vue:       charts-vue.umd.min.js
@carbon/charts-vue:  warning  
@carbon/charts-vue: webpack performance recommendations: 
@carbon/charts-vue: You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
@carbon/charts-vue: For more info visit https://webpack.js.org/guides/code-splitting/
@carbon/charts-vue:  WARNING  Compiled with 3 warnings5:48:21 PM
@carbon/charts-vue:  warning  
@carbon/charts-vue: asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
@carbon/charts-vue: This can impact web performance.
@carbon/charts-vue: Assets: 
@carbon/charts-vue:   charts-vue.umd.js (1.73 MiB)
@carbon/charts-vue:  warning  
@carbon/charts-vue: entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
@carbon/charts-vue: Entrypoints:
@carbon/charts-vue:   charts-vue.umd (1.73 MiB)
@carbon/charts-vue:       charts-vue.umd.js
@carbon/charts-vue:  warning  
@carbon/charts-vue: webpack performance recommendations: 
@carbon/charts-vue: You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
@carbon/charts-vue: For more info visit https://webpack.js.org/guides/code-splitting/
@carbon/charts-vue:   File                          Size                   Gzipped
@carbon/charts-vue:   dist/charts-vue.umd.min.js    617.14 KiB             154.13 KiB
@carbon/charts-vue:   dist/charts-vue.umd.js        1772.08 KiB            315.30 KiB
@carbon/charts-vue:   dist/charts-vue.common.js     1771.70 KiB            315.19 KiB
@carbon/charts-vue:   Images and other types of assets omitted.

**Comment by theiliad** [comment]
Interesting, what happens when you try node 14.x @nstuyvesant?

**Comment by nstuyvesant** [comment]
Succeeds. So this package is dependent upon node 14.21.3 right now. Until we can ascertain the cause, I guess we should revert .nvmrc and change the engines in package.json to specify node ^14.21.3.

There are a lot of old packages referenced so it's going to take some time.

BTW, after the successful build, I upgraded lerna to the latest (I was hoping for more logging capabilities). lerna@^6.5.1 built the project just as well as 3.20.3 with no modifications. The new version is faster and there are some command line arguments that are different so using the latest may be advantageous.


 >  Lerna (powered by Nx)   Successfully ran target demo:build for 5 projects


lerna notice cli v6.5.1
lerna info Executing command in 5 packages: "$LERNA_ROOT_PATH/scripts/copy-demos-to-deploy-dir.sh"
lerna success exec Executed command in 5 packages: "$LERNA_ROOT_PATH/scripts/copy-demos-to-deploy-dir.sh"
✨  Done in 70.56s.

**Comment by nstuyvesant** [comment]
I will submit a separate PR to get it back to running with the newer lerna.

**Pull request merged**
