### PR TITLE
feat(core): Colors, themes & more design updates

### PR DESCRIPTION
**Pull request by theiliad**
### Updates
- Add a color service to provide the new color palette
- Add theme utilities, and default themes (Only high contrast currently)
- Pie & donut sizing and spacing between slices

#246, #252, #254, #255, #243

### CODE REVIEW

**Comment by cal-smith** [comment]
Looking good 🎉 I'll close my draft since you've got all the high points covered

**Comment by theiliad** [comment]
> Looking good 🎉 I'll close my draft since you've got all the high points covered

Cool. We should give ourselves access to our forks, since I could've expanded on your PR

**Comment by theiliad** [comment]
> Looking good 🎉 I'll close my draft since you've got all the high points covered
Cool. We should find a way to collab on PRs, since I could've expanded on yours

**Comment by shixiedesign** [comment]
Question, so in Carbon we do visual reviews in the PR thread. This thread might get really long because all the charts updates are in one PR. Is there a different place you guys do visual reviews before merge? Or should we split this PR into a few parts so we can merge the charts one by one as soon as it is ready?

**Comment by theiliad** [comment]
@shixiedesign This PR will mostly focus on some of the obvious or immediate changes we're going to merge (once colors are approved we will probably go ahead an merge this, then open up separate PRs for the nitty gritty of the rest of the component related updates)

Therefore, you're welcome to share your review here 🙂

**Comment by theiliad** [comment]
@shixiedesign Added all 3. For [Theme 2] that you sent, I added another variation teal `Teal 70` that I was hoping you can review as well.

Here are the themes:
[Theme 1] => https://deploy-preview-261--carbon-charts.netlify.com/?experimental=true&theme=1
[Theme 2] => https://deploy-preview-261--carbon-charts.netlify.com/?experimental=true&theme=2
[Theme 2 + teal 70] => https://deploy-preview-261--carbon-charts.netlify.com/?experimental=true&theme=3
[Theme 3 (dark)] => https://deploy-preview-261--carbon-charts.netlify.com/?experimental=true&theme=4

**Comment by jeoffw** [comment]
Can we add a Charts page to the main site (possibly linking to this site) so this is actually discoverable?

**Comment by zvonimirfras** [comment]
@jeoffw yes please 😃

**Comment by theiliad** [comment]
@zvonimirfras @cal-smith
My final commit in this PR (no design changes @shixiedesign).

I changed the export `themes` to `colorPalettes` because I think the word theme can be interpreted as more than what this PR does.

We can explore the possibility of "themes" at some point, but I'd like to call the newly added service color palettes.

Feel free to merge after approval 💯

**Pull request merged**
