### PR TITLE
Update package.json for Angular 13 support

### PR DESCRIPTION
**Pull request by nstuyvesant**
### Updates
- list
- out
- updates
- here (and don't forget to link the issues)

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Review by Akshat55 — APPROVED** [review]

**Review by theiliad — CHANGES_REQUESTED** [review]
seems like builds failed due to this

**Comment by theiliad** [comment]
@nstuyvesant could you also provide a sample repo/sandbox where you tested things with angular13?

**Comment by nstuyvesant** [comment]
Sure - will need to construct something that doesn't use my employer's code. Might take me a few days.

**Comment by nstuyvesant** [comment]
> @nstuyvesant could you also provide a sample repo/sandbox where you tested things with angular13?

Here's an example from the Storybook using Angular 13.3.2... https://github.com/nstuyvesant/carbon-angular-13

**Comment by nstuyvesant** [comment]
> > > @nstuyvesant could you also provide a sample repo/sandbox where you tested things with angular13?
> > 
> > 
> > Here's an example from the Storybook using Angular 13.3.2... https://github.com/nstuyvesant/carbon-angular-13
> 
> Perfect, thank you @nstuyvesant.
> 
> I can also add your example repo to our README if you'd like (we should probably rename it to `carbon-charts-angular-13` though)

Happy to have it shared - thank you!

**Comment by theiliad** [comment]
@nstuyvesant Could you pls add a license to the repo, and could you pls rename to `carbon-charts-angular-13`?

**Comment by nstuyvesant** [comment]
> @nstuyvesant Could you pls add a license to the repo, and could you pls rename to `carbon-charts-angular-13`?

Updated! Here's the new URL to the repo... https://github.com/nstuyvesant/carbon-charts-angular-13

**Comment by theiliad** [comment]
> > @nstuyvesant Could you pls add a license to the repo, and could you pls rename to `carbon-charts-angular-13`?
> 
> Updated! Here's the new URL to the repo... https://github.com/nstuyvesant/carbon-charts-angular-13

thanks! here's the PR https://github.com/carbon-design-system/carbon-charts/pull/1350

**Pull request merged**
