### PR TITLE
create StyleSheet containing chart styles for all themes

### PR DESCRIPTION
**Pull request by metonym**
This PR creates an additional StyleSheet to support dynamic, client-side theming. Addresses #966 

This creates the following files in `core/dist`:

- styles-all.css
- styles-all.css.map
- styles-all.min.css
- styles-all.min.css.map

### Updates

- feat(core): create StyleSheet containing chart styles for all themes

### Usage

Update the theme dynamically by setting the `"theme"` attribute on the HTML element (`document.documentElement`).

```svelte
<script>
    import { BarChartSimple } from "@carbon/charts-svelte";
    import "@carbon/charts/styles-all.css";
  
    let theme = ''; // default theme is white
  
    $: document.documentElement.setAttribute("theme", theme);
  </script>
  
  <button on:click={() => (theme = "")}>Set white</button>
  <button on:click={() => (theme = "g10")}>Set g10</button>
  <button on:click={() => (theme = "g90")}>Set g90</button>
  <button on:click={() => (theme = "g100")}>Set g100</button>
  
  <BarChartSimple
    data={[
      { group: "Qty", value: 65000 },
      { group: "More", value: 29123 },
      { group: "Sold", value: 35213 },
      { group: "Restocking", value: 51213 },
      { group: "Misc", value: 16932 },
    ]}
    options={{
      title: "Simple bar (discrete)",
      height: "400px",
      axes: {
        left: { mapsTo: "value" },
        bottom: { mapsTo: "group", scaleType: "labels" },
      },
    }}
  />
  
```

### Demo screenshot or recording

https://user-images.githubusercontent.com/10718366/126538034-46b5844f-c61d-43cd-b6c6-4d65554ba6e1.mov

### CODE REVIEW

**Comment by theiliad** [comment]
@metonym how large is the final css file? not sure if this is a good idea

**Comment by metonym** [comment]
@theiliad The uncompressed size for `styles-all.min.css` is 330 KB.

The alternative proposed in #966 is to dynamically update the external StyleSheet from unpkg, which can be limiting.

**Comment by theiliad** [comment]
> @theiliad The uncompressed size for `styles-all.min.css` is 330 KB.
> 
> The alternative proposed in #966 is to dynamically update the external StyleSheet from unpkg, which can be limiting.

would an app need to use all 4 themes? would it be 1 light theme + 1 dark instead?

**Comment by theiliad** [comment]
we have to rethink this, possibly switching to CSS custom properties...

**Comment by ispyinternet** [comment]
@metonym is there a working option to do this, in older versions the following setup was giving me dynamic chart themes, but trying to compile this now is throwing errors, I'm trying various combinations of imports but can't seem to land on a working solution

```
html[theme="g90"] {
    @import "~@carbon/charts/styles/styles-g90.scss";

}

html[theme="g10"] {
    @import "~@carbon/charts/styles/styles-g10.scss";
}
```

**Comment by theiliad** [comment]
Btw, with a carbon v11 migration we'll probably solve this through CSS custom properties

**Comment by ispyinternet** [comment]
Cool, what's the timeline on that?

**Pull request closed without merging**
