### PR TITLE
refactor(tools.ts): stop using a namespace for Tools

### PR DESCRIPTION
**Pull request by wkeese**
### Updates

- Stop using a namespace in tools.ts.  It's unnecessary and breaks tree shaking.
- Update other modules as per tools.ts changes.
- This is just part of the steps I think should be taken to make carbon-charts more tree-shaking friendly.  Other steps would include:
1) Replace `import * as Tools from "../tools"` with `import { mergeDefaultChartOptions, ... } from "../tools"`. 
2) Import lodash-es methods directly rather than re-exporting them from tools.ts.

Refs #1507.

Please use the [ignore spacing option](https://github.com/carbon-design-system/carbon-charts/pull/1509/files?diff=unified&w=1) when reviewing changes.

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by wkeese** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by theiliad** [comment]
Hi @wkeese I think you need to push an update to get the DCO Assistant to update

**Review by theiliad — APPROVED** [review]
LGTM

**Comment by theiliad** [comment]
recheck

**Pull request merged**
