### PR TITLE
Zoom and Scroll Functionality (sliders)

### PR DESCRIPTION
**Pull request by licarijd**
### Updates
- handles for modifying max/min values
- draggable sliders

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/IBM/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by cal-smith** [comment]
Related #131

**Comment by theiliad** [comment]
Great work, still seeing this issue:
https://i.imgur.com/aduJNUF.mp4

**Comment by theiliad** [comment]
Good work fixing that bug @licarijd 💯

I think the fix created another issue:
https://i.imgur.com/d76iPXi.mp4

**Comment by theiliad** [comment]
@licarijd Closing this for now as sliders are being re-specced. Let me know if you'd like to be kept in the loop once new specs come out

**Pull request closed without merging**
