### PR TITLE
pie/donut: disable labels (and callouts)

### PR DESCRIPTION
**Pull request by natashadecoste**
### Updates
- there is no respacing of the pie/donut so that the labels can be toggled on/off in different UIs/dashboards

### Demo screenshot or recording
labels off
image
labels on
image

### configs
```
pie: {
    labels: {
        enabled: false | true (defaults to true)
    }
}
```

related to #917 

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Review by theiliad — CHANGES_REQUESTED** [review]
Does the pie not translate anymore and not accomodate for rendered callouts? and is @jeanservaas ok with this?

**Comment by natashadecoste** [comment]
> Does the pie not translate anymore and not accomodate for rendered callouts? and is @jeanservaas ok with this?

 

> Does the pie not translate anymore and not accomodate for rendered callouts? and is @jeanservaas ok with this?

```		
if (calloutData.length > 0) {
	pieTranslateY += Configuration.pie.yOffsetCallout;
}
```

if **we do add** the padding when the labels are disabled - and then the labels are toggled back on enabled: the pie might move if you have **no calloutData** (slices are all a bigger size)

if **we don't add** padding when labels are disabled - then they are toggled back on enabled: the pie might still move around if there **is calloutData** but wont move if there isnt

the only way to have the pie stay in the same place would be if we wanted to add the callout padding regardless of whether there is callouts being rendered. this also would make sure when the legend is being used to toggle on/off datagroups that there isnt movement of the pie graph

**Comment by theiliad** [comment]
> > Does the pie not translate anymore and not accomodate for rendered callouts? and is @jeanservaas ok with this?
> 
> ```
> if (calloutData.length > 0) {
> 	pieTranslateY += Configuration.pie.yOffsetCallout;
> }
> ```
> 
> if **we do add** the padding when the labels are disabled - and then the labels are toggled back on enabled: the pie might move if you have **no calloutData** (slices are all a bigger size)
> 
> if **we don't add** padding when labels are disabled - then they are toggled back on enabled: the pie might still move around if there **is calloutData** but wont move if there isnt
> 
> the only way to have the pie stay in the same place would be if we wanted to add the callout padding regardless of whether there is callouts being rendered. this also would make sure when the legend is being used to toggle on/off datagroups that there isnt movement of the pie graph

if you disable then enable callouts I'd assume that the pie moving wouldn't bee too much of an issue

**Comment by theiliad** [comment]
has @jeanservaas looked at this?

**Comment by tony** [comment]
This looks really good!

Any chance that disabling labels/callouts would also re-orient the box so the rest of the space is used? (If that's extra additional effort - I think it could be - I can also make a separate issue to address whether that's possible)

**Review by sophiiae — APPROVED** [review]

**Review by theiliad — DISMISSED** [review]

**Comment by theiliad** [comment]
@natashadecoste has Jeannie seen this? good to merge?

**Comment by natashadecoste** [comment]
> This looks really good!
> 
> Any chance that disabling labels/callouts would also re-orient the box so the rest of the space is used? (If that's extra additional effort - I think it could be - I can also make a separate issue to address whether that's possible)

updated it 👍

**Comment by tony** [comment]
@natashadecoste 

As for the extra spacing left over when stuff is hidden, will that be handled by this PR?  (I can also make a separate issue for that, if it's easier to look at after). What do you think?

Some context:

image

As a workaround until then, I manually move the container in itself:

``` scss
.chartRow--donut {
  margin-left: -29px;
  margin-top: -25px;
  z-index: -10;
}
```

https://cv-react-v2.git-pull.com/ with `^0.41.28`

image

**Comment by natashadecoste** [comment]
@tony 
posted below you can see that without the labels, the pie expands and is slightly larger. it will never go right under the title because there is space there **intentionally** to allow the title to breathe. 

#### with labels
image

#### without 
image

--- 
you can see here that the pie is taking all of its space.
image


The better workaround for you would be to not use a title (implement the title separately) and then the donut gets all the space
image

**Comment by tony** [comment]
@natashadecoste Thank you for the explanation!  This has been super helpful!

And to clarify, are the screenshots/explanations the present behavior in the stable release, or are we referring to new adjustments in this PR?

> implement the title separately

That's interesting to me - could you steer me to where in the documentation I can find more about this, or potentially [fork my sandbox](https://codesandbox.io/s/carbon-components-hide-labels-donut-0mngj?file=/src/index.js) to show me what that'd look like?

**Comment by natashadecoste** [comment]
> And to clarify, are the screenshots/explanations the present behavior in the stable release, or are we referring to new adjustments in this PR?

Its in this PR

for the title,if you just remove the `title` option you will get the chart without the title & spacer rendered. 
Then you can implement the title separately in your app (in whichever framework) 
Specs for the titles in carbon charts are:
image

**Comment by tony** [comment]
Thank you once again @natashadecoste!

**Review by sophiiae — APPROVED** [review]

**Review by theiliad — APPROVED** [review]

**Pull request merged**
