### PR TITLE
fix(model-csvFile-#1468):time level precision not availabe in date

### PR DESCRIPTION
**Pull request by RiyaJethwa**
### Updates
- #1468 
-Addition of dateFormatter under model property in options object.
-User is now able to format date as per need.
-Changes will be reflected in the subsequent CSV file.

### Demo screenshot or recording
image

### CODE REVIEW

**Comment by RiyaJethwa** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by naegelin** [comment]
issue #1659 should also be addressed by this fix.

**Comment by miedzikd** [comment]
Can I ask if there is any chance to merge that branch? Can I help somehow?

**Comment by theiliad** [comment]
This has already been addressed partially by our `tabularRepModal ` configs
https://charts.carbondesignsystem.com/documentation/interfaces/interfaces.TabularRepCustomizationOptions.html

And will also be addressed by #1710.

Those 2 pieces better address modal customizability (already available), and a general locale interface for dates & numbers (merging soon)

**Pull request closed without merging**
