### PR TITLE
Time series labels bug

### PR DESCRIPTION
**Pull request by ilariaventurini**
We have identified a bug that sometimes produces repeated tick labels. This PR is an improvement proposal.

Ticks are now computed using d3 `nice`:

image

| Before | Now |
|---|---|
| 1 old | 1 new |
| 3 old | 3 new |

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/IBM/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by ilariaventurini** [comment]
@theiliad That's really strange. I look at it

**Comment by caesarsol** [comment]
@theiliad there's something wrong, because in local development we aren't observing any of these issues. 
Maybe an error with the deploy? 

(This netlify deploy is currently 404 btw)

**Comment by theiliad** [comment]
> @theiliad there's something wrong, because in local development we aren't observing any of these issues.
> Maybe an error with the deploy?
> 
> (This netlify deploy is currently 404 btw)

yes I had to replace the Netlify app. would you be able to add a small change (e.g. comment modification) to re-trigger the demos?

**Comment by theiliad** [comment]
@caesarsol I think it could be that 
image

**Comment by theiliad** [comment]
Looks like there are a ton of conflicts here

**Comment by ilariaventurini** [comment]
@theiliad did a merge and solved the conflicts.

**Comment by theiliad** [comment]
I think there's another conflict here

**Pull request merged**
