### PR TITLE
chore: make sass an optional peer dependency of charts

### PR DESCRIPTION
**Pull request by josefaidt**
### Updates

- adds `sass` as an optional peer dep of `@carbon/charts`. The real peer dep is in `@carbon/styles` and rightfully so, therefore I'm not 100% certain this will work the way I expect it to, but it appears optional per the findings in #1440 

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by nstuyvesant** [comment]
While `@carbon/charts` exports SCSS files, it is not required that an app that uses this component library has sass.

For example, you might import only the CSS files. Along those lines, my recommendation would be to not make `sass` a peerDependency.

IMO, I would reserve peerDependencies to indicate "this component library won't work with X or Y."

**Comment by theiliad** [comment]
@nstuyvesant agreed

**Comment by nstuyvesant** [comment]
@josefaidt - I ran into an issue where `@carbon/charts` StackBlitz examples require `sass` even though they are only importing CSS from `@carbon/styles`.

The problem is that `@carbon/styles` requires `sass` (unnecessarily). So I added [this PR](https://github.com/carbon-design-system/carbon/pull/14131) to that project to flag the `sass` peerDependency as optional.

Wrote this here as I'm wondering if this is actually your issue. Your PR for `@carbon/charts` is the same as my PR for `@carbon/styles`. The difference is that `@carbon/styles` has `sass` as a peerDependency while `@carbon/charts` does not.

If you think this solves your issue, please close this PR.

**Comment by josefaidt** [comment]
Hey @nstuyvesant thanks for the update! I'll close this PR :)

**Comment by nstuyvesant** [comment]
I have read the DCO document and I hereby sign the DCO.

**Pull request closed without merging**
