### PR TITLE
Set toolbar control background to transparent

### PR DESCRIPTION
**Pull request by hlyang397**
### Updates
- use fill:none to allow transparent toolbar control background. It fixes the problem when user changes the chart background color.

### Demo screenshot or recording
No UI change in demo.

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Review by theiliad — CHANGES_REQUESTED** [review]
Why would the user change the background of the chart in any of the 4 themes? That'd probably result in a lack of compliance with the design language...?

**Comment by hlyang397** [comment]
> Why would the user change the background of the chart in any of the 4 themes? That'd probably result in a lack of compliance with the design language...?
When we set the control background to transparent (fill:none), it could work no matter if user like to follow design language or not.

Our application does use the g90 theme, but we also use a little different background color for chart area.

**Comment by joshkimmell** [comment]
If you don't feel comfortable allowing developers to set the background to transparent, why not give them more theme choices? In our case, the sparkline provides a visual element to our query cards, which are IDL compliant and accessible. We need the background to be transparent because of our card states, which include hover and disabled. Unless you're going to include states in the chart, transparency is the only thing that would work here.

**Comment by theiliad** [comment]
> If you don't feel comfortable allowing developers to set the background to transparent, why not give them more theme choices? In our case, the sparkline provides a visual element to our query cards, which are IDL compliant and accessible. We need the background to be transparent because of our card states, which include hover and disabled. Unless you're going to include states in the chart, transparency is the only thing that would work here.

I think that we definitely need to discuss this on the guild call https://www.carbondesignsystem.com/whats-happening/meetups#data-visualization-weekly-playbackwednesdays-11am12pm-central

**Review by theiliad — APPROVED** [review]

**Comment by hlyang397** [comment]
@natashadecoste @cal-smith
Could you help to review this PR ? Thanks.

**Review by cal-smith — APPROVED** [review]
Makes sense to me 👍

**Pull request merged**
