### PR TITLE
Line underflow 2

### PR DESCRIPTION
**Pull request by licarijd**
### Updates
add clip path to x grid
fixes underflow issues such as https://github.com/carbon-design-system/carbon-charts/issues/101

### Demo screenshot or recording
https://www.loom.com/share/42b8982fc5c9470a92a3e3daff877ef8

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/IBM/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by cal-smith** [comment]
I'm not sure this is entirely the right solution ... this looks broken:

image

But the line extending past the x axis is also non-ideal ... I'm just not sure which looks _less_ broken

**Comment by theiliad** [comment]
Thanks @licarijd. This is something I suggest design to take a look at first.

@cameroncalder @shixiedesign

**Comment by shixiedesign** [comment]
Can i get a bit more context/description on use case around this? Why is the path clipped and is it desirable?

**Comment by theiliad** [comment]
> Can i get a bit more context/description on use case around this? Why is the path clipped and is it desirable?

So this is a somewhat of an edge case where you might have a few points on the very bottom of your y-axis, and lots of fluctuations. In such cases, a small part of the curve will go out of the chart, which can look a bit off.

**Comment by theiliad** [comment]
@licarijd  I closed this PR for now since it's been inactive for a long time. Let me know if you'd still like to work on it and we can re-open.

**Pull request closed without merging**
