### PR TITLE
OK to merge: fix(pr-1540): load IIFE into bundle

### PR DESCRIPTION
**Pull request by nstuyvesant**
Makes 'dom-to-image-more' external in rollup config so consuming projects don't need to deal with this.

### Updates
- list
- out
- updates
- here (and don't forget to link the issues)

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/carbon-design-system/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by nstuyvesant** [comment]
I have two PRs for `dom-to-image-more` pending merge. These solve errors from assuming Node and window are defined.

**Comment by nstuyvesant** [comment]
Also, I removed the warning for the D3 circular dependencies. I tried to get the maintainers of D3 to resolve it but they won't so no need to keep displaying this.

**Comment by nstuyvesant** [comment]
Very unfortunate that `dom-to-image-more` is an IIFE as it defeats tree-shaking and `carbon-charts` only uses two functions.

**Comment by theiliad** [comment]
@nstuyvesant since your PR there was merged, is this one good to merge?

**Comment by nstuyvesant** [comment]
Arg... they modified my PR from:
```js
const ELEMENT_NODE = typeof Node === 'undefined' ? 1 : Node.ELEMENT_NODE || 1;
```
to
```js
const ELEMENT_NODE = (Node && Node.ELEMENT_NODE) || 1;
```
with does not work.

So we're still getting...
```
[!] ReferenceError: Node is not defined
ReferenceError: Node is not defined
    at /Users/nates/dev/rebase/node_modules/dom-to-image-more/src/dom-to-image-more.js:8:26
    at Object.<anonymous> (/Users/nates/dev/rebase/node_modules/dom-to-image-more/src/dom-to-image-more.js:1392:3)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.require.extensions.<computed> [as .js] (/Users/nates/dev/rebase/node_modules/rollup/dist/bin/rollup:835:17)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/nates/dev/rebase/packages/core/rollup.config.js:13:34)
```
and...
```
[!] ReferenceError: window is not defined
ReferenceError: window is not defined
    at /Users/nates/dev/rebase/node_modules/dom-to-image-more/src/dom-to-image-more.js:50:70
    at Object.<anonymous> (/Users/nates/dev/rebase/node_modules/dom-to-image-more/src/dom-to-image-more.js:1392:3)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Object.require.extensions.<computed> [as .js] (/Users/nates/dev/rebase/node_modules/rollup/dist/bin/rollup:835:17)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/nates/dev/rebase/packages/core/rollup.config.js:13:34)
```
which is the other PR I submitted. I will open an issue with dom-to-image-more.

**Comment by nstuyvesant** [comment]
The modification they made to my PR really should work as `Node` is falsy so it should short-circuit rather than error. Showed the package maintainer what's happening. BTW, it does not happen with vite/esbuild.

**Comment by nstuyvesant** [comment]
The package `dom-to-image-more` was just updated to fix the rollup issue. @theiliad  - this one is good to go.

**Review by theiliad — APPROVED** [review]
LGTM

**Pull request merged**
