### PR TITLE
Add more unit tests

### PR DESCRIPTION
**Pull request by Donisius**
### Updates
- Added additional unit tests for legend and title

### Review checklist (for reviewers only)
- [ ] Demos all features
- [ ] Documented/annotated
- [ ] Matches UI/UX specs
- [ ] Meets the [code style guide](https://github.com/IBM/carbon-charts/wiki/Code-style-guide)
- [ ] Accessible
- [ ] Mobile first (responsive)
- [ ] RTL support (bidirectional text)
- [ ] Performant (limited bloat)

### CODE REVIEW

**Comment by natashadecoste** [comment]
@Donisius 
you are missing the 

```
	afterEach(function() {
		this.testEnvironment.destroy();
	});
```

from axis.spec.ts. After adding that in, you can remove the `selectAll()...remove()` from title.spec.ts and from legend.spec.ts and it works just fine 👍

**Comment by Donisius** [comment]
@natashadecoste 
For some reason adding the afterEach in `axis.spec.ts` specifically causes the tests to fail sometimes. And the `selectAll()...remove()` is needed because if you run the tests multiple times it sometimes causes the `too late already running` transition error.

**Comment by theiliad** [comment]
@Donisius are transitions working better with the updates merged today?

**Comment by Donisius** [comment]
> @Donisius are transitions working better with the updates merged today?

I am still getting the `Uncaught Error: too late; already running thrown` error when I use more than one type of chart. Using only one type of chart does not give the transition errors.

**Comment by theiliad** [comment]
image

**Pull request closed without merging**
